CREATE DATABASE IF NOT EXISTS `xerte-db`
	CHARACTER SET = 'utf8'
    COLLATE = 'utf8_unicode_ci';
CREATE OR REPLACE USER xerte@'%' IDENTIFIED BY 'AYUaFW5zhQvNzHHcv2q67gzfmMtvmpAD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON `xerte-db`.* TO 'xerte'@'%';    
    
CREATE DATABASE IF NOT EXISTS `moodle-db`
	CHARACTER SET = 'utf8'
    COLLATE = 'utf8_unicode_ci';    
CREATE OR REPLACE USER moodle@'%' IDENTIFIED BY 'YVNex3CHq4yc2DzHYVNex3CHq4yc2DzH';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON `moodle-db`.* TO 'moodle'@'%';