CREATE DATABASE IF NOT EXISTS `xerte-db`
	CHARACTER SET = 'utf8'
    COLLATE = 'utf8_unicode_ci';
CREATE OR REPLACE USER xerte@'%' IDENTIFIED BY 'AYUaFW5zhQvNzHHcv2q67gzfmMtvmpAD';
GRANT ALL PRIVILEGES ON `xerte-db`.* TO 'xerte'@'%' WITH GRANT OPTION;    
    
CREATE DATABASE IF NOT EXISTS `moodle-db`
	CHARACTER SET = 'utf8'
    COLLATE = 'utf8_unicode_ci';    
CREATE OR REPLACE USER moodle@'%' IDENTIFIED BY 'YVNex3CHq4yc2DzHYVNex3CHq4yc2DzH';
GRANT ALL PRIVILEGES ON `moodle-db`.* TO 'moodle'@'%' WITH GRANT OPTION;