version: '2'
services:
  samba:
    image: trnape/rpi-samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "445:445"
    networks:
      - rpi4learning
    command: "-u '${SAMBA_USER}:${SAMBA_PASSWORD}' -s 'docker:/share/data:rw:${SAMBA_USER}'"  
    volumes:
      - "/home/pi/docker:/share/data"
      
networks:
     rpi4learning:
        external: true     