version: '2'
services:
  moodle:
    image: rpi4learningbox/moodle:${MOODLE_VERSION}
    container_name: moodle
    restart: unless-stopped
    ports:
      - "81:80"
    networks:
      - rpi4learning
    env_file: ${PWD}/.env
    volumes:
      - "${PWD}/config.php:/var/www/html/config.php"
        
networks:
     rpi4learning:
        external: true