version: '2'
services:

    mongo:
        image: mongo:4.4.5
        container_name: learninglocker_mongo
        restart: unless-stopped
        networks:
          - rpi4learning  
        ports:
            - "27017:27017"
        volumes:
            - "${PWD}/data/mongo:/data/db"

    redis:
        image: redis:4-alpine
        container_name: learninglocker_redis
        restart: unless-stopped
        networks:
          - rpi4learning  

    xapi:
        image: learninglocker/xapi-service:4.0.1
        container_name: learninglocker_xapi
        restart: unless-stopped
        networks:
          - rpi4learning  
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - MONGO_DB=learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - mongo
            - redis          
        volumes:
            - "${PWD}/data/xapi-storage:/usr/src/app/storage"

    api:  
        image: rpi4learningbox/learninglocker2-app:${LL_VERSION}
        container_name: learninglocker_api
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        networks:
          - rpi4learning  
        depends_on:
            - mongo
            - redis            
        volumes:
            - "${PWD}/data/app-storage:/opt/learninglocker/storage"

    ui: 
        image: rpi4learningbox/learninglocker2-app:${LL_VERSION}
        container_name: learninglocker_ui
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        networks:
          - rpi4learning  
        depends_on:
            - mongo
            - redis
            - api             
        volumes:
            - "${PWD}/data/app-storage:/opt/learninglocker/storage"
            - "${PWD}/data/ui-logs:/opt/learninglocker/logs"

    worker:  
        image: rpi4learningbox/learninglocker2-app:${LL_VERSION}
        container_name: learninglocker_worker
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node worker/dist/server"
        restart: unless-stopped
        networks:
          - rpi4learning  
        depends_on:
            - mongo
            - redis           
        volumes:
            - "${PWD}/data/app-storage:/opt/learninglocker/storage"

    nginx: 
        image: rpi4learningbox/learninglocker2-nginx:1.20.0
        container_name: learninglocker_nginx
        environment:
            - DOMAIN_NAME
        restart: unless-stopped
        networks:
          - rpi4learning  
        depends_on:
            - ui
            - xapi
        ports:
            - "2443:443"
            - "280:80"        

networks:
     rpi4learning:
        external: true    