version: '2'
services:

    mongo:
        image: mongo:4.4.5
        restart: unless-stopped
        volumes:
            - "${DATA_LOCATION}/mongo:/data/db"
        ports:
            - "27017:27017"

    redis:
        image: redis:4-alpine
        restart: unless-stopped

    xapi:
        image: learninglocker/xapi-service:4.0.1
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - MONGO_DB=learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/xapi-storage:/usr/src/app/storage"

    api:
        image: up2university/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    ui:
        image: up2university/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
            - api
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
            - "${DATA_LOCATION}/ui-logs:/opt/learninglocker/logs"

    worker:
        image: up2university/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    nginx:
        image: up2university/learninglocker2-nginx:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
        restart: unless-stopped
        depends_on:
            - ui
            - xapi
        ports:
            - "2443:443"
            - "280:80"
        volumes:
            - "${DATA_LOCATION}/cert/fullchain.pem:/root/ssl/fullchain.pem:ro"
            - "${DATA_LOCATION}/cert/privkey.pem:/root/ssl/privkey.pem:ro"

